### ISSUE TITLE
Type-safe signals from Godot-defined structs

### ISSUE THREAD

**Issue by atollk** [godot-rust/gdext#1108]
I just saw that type-safe signals have recently been added to godot-rust, including a chapter in the book. That chapter solely focuses on signals defined in custom classes. Is there a way to use signals defined by the Godot library in types like `Node` in a type-safe way? Is this still work in progress (considering it's just on the master branch, not a released version)?

```rust
#[godot_api]
impl IArea2D for Player {
    fn ready(&mut self) {
        self.base().signals().body_entered().connect(/* ... */);
    }
}
```

**Comment by Bromeon** [comment]
I just implemented this, see linked PR 🙂

**Comment by atollk** [comment]
Awesome!
I noticed that it does work for some structs now but it still doesn't for some others. So, I understand that this is still in very active development then and it probably isn't a good idea to use signals for now?

**Comment by Bromeon** [comment]
> I noticed that it does work for some structs now but it still doesn't for some others.

Can you be specific? So far, signals are only defined on the classes that declare them, not derived ones.
But what "doesn't work"?


> So, I understand that this is still in very active development then and it probably isn't a good idea to use signals for now?

Yes, signal implementation is an incremental process, and 1 PR being merged doesn't mean "every feature one can ever wish for is now there" 😀 see also https://github.com/godot-rust/gdext/issues/1112#issuecomment-2765671329.

Whether it's a good idea depends on your use case. I don't expect major breaking changes, and in several places it's already much better than the alternative (untyped signals). But of course, it still needs ironing out, and suggestions on how to implement things are welcome.


---

Fun coincidence: 😎 

![111111](https://github.com/user-attachments/assets/0ced4c94-cd0d-4a54-b284-98552d4c1e98)

**Comment by atollk** [comment]
> Whether it's a good idea depends on your use case.

I meant more like, because it's an incremental process, when I start using type-safe signals now, I will probably run into missing or buggy functionality, at which point it is unclear to me if I should open another issue or if that's already known, just not implemented.

> But what "doesn't work"?

Specifically, the `Button` struct does not implement `WithSignals`, so it cannot be used with the new interface.
